---
- name: Build Switch configuration
  hosts: [ FABRIC ]
  collections:
    - arista.avd

  tasks:

    - name: build local folders
      tags: [build]
      import_role:
        name: arista.avd.build_output_folders

    - name: generate intented variables
      tags: [build]
      import_role:
        name: arista.avd.eos_l3ls_evpn

    - name: generate device intended config and documentation
      tags: [build]
      import_role:
        name: arista.avd.eos_cli_config_gen

    - name: deploy configuration to device
      tags: [deploy, never]
      import_role:
          name: arista.avd.eos_config_deploy_eapi

    - name: validate states on EOS devices
      tags: [validate, never]
      import_role:
        name: arista.avd.eos_validate_state

    - name: Collect commands
      tags: [snapshot, never]
      import_role:
        name: eos_snapshot